version: '3'

services:
  app:
    build:
      context: node
    networks:
      - node-mysql-nginx-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    container_name: app
    depends_on:
      - db
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-mysql-nginx-network
  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    networks:
      - node-mysql-nginx-network
    ports:
      - "8080:80"
    entrypoint: dockerize -wait tcp://app:3000 -timeout 20s nginx -g "daemon off;"

networks:
  node-mysql-nginx-network:
    driver: bridge